parameters:
    hadonra_address.address.repository.class: Hadonra\Bundle\AddressBundle\Repository\AddressRepository

services:
    hadonra_address.address.repository:
        class: %hadonra_address.address.repository.class%
        arguments:
            - "@doctrine.orm.entity_manager"
