parameters:
    hadonra_address.address.service.class: Hadonra\Bundle\AddressBundle\Service\AddressService

services:
    hadonra_address.address.service:
        class: %hadonra_address.address.service.class%
        arguments:
            - "@hadonra_address.address.repository"

