parameters:
#    hadonra_address.example.class: Hadonra\Bundle\AddressBundle\Example

services:
#    hadonra_address.example:
#        class: %hadonra_address.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
